"use client"
import Link from "next/link"
import { ArrowRight, Crown, LockKeyhole, Trophy } from "lucide-react"
import { useEffect,useState } from "react"
import { api } from "@/lib/api"
import type { FantasyPoints, FantasyTeam, LeaderboardEntry, User } from "@/lib/types"
import { Button,Card,ErrorBox,Loading,PageTitle } from "@/components/ui"
export default function DashboardPage(){const [user,setUser]=useState<User|null>(null);const [team,setTeam]=useState<FantasyTeam|null>(null);const [points,setPoints]=useState<FantasyPoints|null>(null);const [rank,setRank]=useState<number|null>(null);const [error,setError]=useState<unknown>(null);const [creating,setCreating]=useState(false);useEffect(()=>{(async()=>{try{const u=await api.me();setUser(u);const leaders=await api.leaderboard();const entry=leaders.find(x=>x.username===u.username);if(entry){const ft=await api.fantasy(entry.fantasy_team_id);setTeam(ft);setPoints(await api.fantasyPoints(ft.id));setRank(entry.rank)} }catch(e){setError(e)}})()},[]);async function create(){setCreating(true);setError(null);try{const ft=await api.createFantasyTeam();setTeam(ft)}catch(e){setError(e)}finally{setCreating(false)}}if(!user&&error instanceof Error&&"status" in error)return <main className="mx-auto max-w-md px-5 py-24"><ErrorBox error={error}/><Link href="/login" className="mt-5 inline-block text-sm font-semibold text-[#f4d35e]">Log in →</Link></main>;return <main className="mx-auto max-w-7xl px-5 py-16 lg:px-8">{error&&<ErrorBox error={error}/>} {!user?<Loading/>:<><PageTitle eyebrow="Manager dashboard" title={`Hey, ${user.username}.`} description="Your fantasy command center. Your squad, score and tournament status live here."/><div className="mt-10 grid gap-4 sm:grid-cols-3"><Metric icon={Crown} label="Total points" value={points?String(points.total_points):"—"}/><Metric icon={Trophy} label="Leaderboard rank" value={rank?`#${rank}`:"—"}/><Metric icon={LockKeyhole} label="Squad" value={team?`${team.player_ids.length}/4`:"Not drafted"}/></div>{team?<Card className="mt-8 p-7"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#f4d35e]">Fantasy team #{team.id}</p><h2 className="mt-2 font-mono text-2xl font-bold">Your squad is {team.player_ids.length===4?"locked in":"not complete"}.</h2><p className="mt-2 text-sm text-zinc-500">Captain: {team.captain_player_id?`player #${team.captain_player_id}`:"not selected"}</p></div><Link href="/fantasy-team"><Button>Manage squad <ArrowRight className="size-4"/></Button></Link></div></Card>:<Card className="mt-8 p-8"><h2 className="font-mono text-2xl font-bold">Create your fantasy team</h2><p className="mt-2 max-w-xl text-sm leading-6 text-zinc-500">The backend allows one fantasy team per account. Once created, you can select four players from four different real teams.</p><Button loading={creating} onClick={create} className="mt-5">Create fantasy team</Button></Card>}</>}</main>}
function Metric({icon:Icon,label,value}:{icon:typeof Trophy,label:string,value:string}){return <Card className="p-5"><Icon className="mb-8 size-5 text-[#f4d35e]"/><p className="text-xs uppercase tracking-[.18em] text-zinc-600">{label}</p><p className="mt-1 font-mono text-3xl font-black">{value}</p></Card>}
